// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentACarApi.Models;

namespace RentACarApi.Migrations
{
    [DbContext(typeof(RentACarContext))]
    partial class RentACarContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RentACarApi.Models.Booking", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<short>("CarId");

                    b.Property<double>("DropLat");

                    b.Property<double>("DropLng");

                    b.Property<string>("Drop_address");

                    b.Property<string>("Drop_city");

                    b.Property<DateTime>("Drop_date");

                    b.Property<double>("PickUpLat");

                    b.Property<double>("PickUpLng");

                    b.Property<string>("Pickup_address");

                    b.Property<string>("Pickup_city");

                    b.Property<DateTime>("Pickup_date");

                    b.Property<short>("TotalPrice");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("BookingItems");
                });

            modelBuilder.Entity("RentACarApi.Models.CarDetails", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CarName");

                    b.Property<short>("CarRate");

                    b.Property<short>("CarSeats");

                    b.HasKey("Id");

                    b.ToTable("CarItems");
                });

            modelBuilder.Entity("RentACarApi.Models.Booking", b =>
                {
                    b.HasOne("RentACarApi.Models.CarDetails", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
